name: Build examples

on:
  push:
  pull_request:
jobs:
  # build-demo-granular-synthesizer-web:
  #   runs-on: ubuntu-latest
  #
  #   defaults:
  #     run:
  #       working-directory: examples/counter
  #
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #
  #     - name: Set up Node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version-file: 'demos/granular_synthesizer_web/.nvmrc'
  #
  #     - name: Install dependencies
  #       run: npm ci
  #
  #     - name: Build project
  #       run: npm run build

  build-counter:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: examples/counter

    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install stable
          rustup target add wasm32-unknown-unknown

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Install Trunk
        run: |
          cargo install --locked trunk

      - name: Build
        run: |
          trunk build
