name: Build examples

on:
  push:
  pull_request:
jobs:
  build-leptos-in-react:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: examples/leptos_in_react

    steps:
      - uses: actions/checkout@v2

        # rust toolchain & build
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install stable
          rustup target add wasm32-unknown-unknown

      - name: Install cargo tooling
        run: |
          cargo install wasm-bindgen-cli --vers "0.2.92"
          cargo install cargo-make

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
          cargo make --version

      - name: Build wasm dependencies
        run: cargo make build-dev

        # JS toolchain and build
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2

      - name: Install yarn
        run: npm install --global yarn

      - name: Install JS dependencies
        run: yarn

      - name: Build project
        run: yarn build

  build-counter:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: examples/counter

    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install stable
          rustup target add wasm32-unknown-unknown

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Install Trunk
        run: |
          cargo install --locked trunk

      - name: Build
        run: |
          trunk build
